### ISSUE TITLE
Would like to create mathematics interpretation for Anuja AI [Hacktober]

### ISSUE THREAD

**Issue by dancinglightning** [Anuja2512/Answering_Machine#32]
I would like to add a few functions besides the if-elif outside the call_Anuja function so that Anuja is able to understand mathematical statements given by the user even if it isn't oblivious or stated separately.

This can be like "What is twenty plus thirty two" and the statement which will be given as output will be "I think the answer is fifty two".

Please give this feature a thought.

Thanks!

**Comment by Karthik-PM** [comment]
assign me this issue please

**Comment by Anuja2512** [comment]
Hey I have assigned you the issue. Please feel free to contribute more.
Happy Hacktober :)

**Comment by Karthik-PM** [comment]
thanks :)
